name: CI
on:
  push:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Use Node.js 16.x
        id: tests-workflow
        uses: actions/setup-node@v4
        with:
          node-version: 16.14.0
          cache: npm
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules/.cache/eslint/
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json', '**/.eslintrc.js') }}
      - name: Install
        run: npm ci
      - name: Lint
        run: npm run lint
